/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudera.sa.examples.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.cloudera.sa.examples.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favourite_color\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence favourite_color;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public User() {}

  /**
   * All-args constructor.
   */
  public User(java.lang.CharSequence name, java.lang.CharSequence favourite_color) {
    this.name = name;
    this.favourite_color = favourite_color;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return favourite_color;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: favourite_color = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'favourite_color' field.
   */
  public java.lang.CharSequence getFavouriteColor() {
    return favourite_color;
  }

  /**
   * Sets the value of the 'favourite_color' field.
   * @param value the value to set.
   */
  public void setFavouriteColor(java.lang.CharSequence value) {
    this.favourite_color = value;
  }

  /** Creates a new User RecordBuilder */
  public static com.cloudera.sa.examples.avro.User.Builder newBuilder() {
    return new com.cloudera.sa.examples.avro.User.Builder();
  }
  
  /** Creates a new User RecordBuilder by copying an existing Builder */
  public static com.cloudera.sa.examples.avro.User.Builder newBuilder(com.cloudera.sa.examples.avro.User.Builder other) {
    return new com.cloudera.sa.examples.avro.User.Builder(other);
  }
  
  /** Creates a new User RecordBuilder by copying an existing User instance */
  public static com.cloudera.sa.examples.avro.User.Builder newBuilder(com.cloudera.sa.examples.avro.User other) {
    return new com.cloudera.sa.examples.avro.User.Builder(other);
  }
  
  /**
   * RecordBuilder for User instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence favourite_color;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudera.sa.examples.avro.User.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudera.sa.examples.avro.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favourite_color)) {
        this.favourite_color = data().deepCopy(fields()[1].schema(), other.favourite_color);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing User instance */
    private Builder(com.cloudera.sa.examples.avro.User other) {
            super(com.cloudera.sa.examples.avro.User.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.favourite_color)) {
        this.favourite_color = data().deepCopy(fields()[1].schema(), other.favourite_color);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.cloudera.sa.examples.avro.User.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.cloudera.sa.examples.avro.User.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'favourite_color' field */
    public java.lang.CharSequence getFavouriteColor() {
      return favourite_color;
    }
    
    /** Sets the value of the 'favourite_color' field */
    public com.cloudera.sa.examples.avro.User.Builder setFavouriteColor(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.favourite_color = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'favourite_color' field has been set */
    public boolean hasFavouriteColor() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'favourite_color' field */
    public com.cloudera.sa.examples.avro.User.Builder clearFavouriteColor() {
      favourite_color = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public User build() {
      try {
        User record = new User();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.favourite_color = fieldSetFlags()[1] ? this.favourite_color : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
